originator: KinesisProducer
server:
 port: 64398
management:
 port: 8082
 context-path: /manage
security:
 user:
  name: admin
  password: 2c76788d-e661-49fd-baba-4b41e7c1dd47

spring:
  cloud:
    stream:
      bindings:
        ordersOut: 
          destination: lab_csi
          content-type: application/json
          producer: 
            partitionKeyExpression: "1" 
        ordersIn:
          destination: lab_csi
          content-type: application/json
        myOrdersIn:
          destination: lab_csi2
          content-type: application/json

cloud:  
  aws:  
    region:  
      static: us-east-1

logging: 
  level:
    com: 
      amazonaws: INFO
    org:
      apache: 
        http: INFO